name: Run notebooks and commits back

on:
  push:
    branches:
      - master

jobs:
  test_build_web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
            python-version: '3.x' 
            architecture: 'x64' 
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Execute notebooks
        run: |
            jupyter nbconvert --execute --inplace WHO-situation-reports.ipynb

      - name: List outputs
        run: |
            ls data
            ls images
            
