name: Run notebooks and commits back data/images

on:
  push:
    branches:
      - master

  schedule: # every 6 hours
    - cron:  '0 */6 * * *'

jobs:
  execute_notebooks:
    runs-on: ubuntu-latest
    container: 
        image: alext234/data-science-selenium/datascience:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            mkdir -p data images 

      - name: Execute notebooks
        run: |
            jupyter nbconvert --execute --inplace *.ipynb   --ExecutePreprocessor.timeout=180
            
      - name: Commit files 
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data images *.ipynb
            git commit -m "Update data, images and notebooks"

      - name: Push to repo
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

            
